import type { Metadata, Viewport  } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import React from 'react';
import { Providers } from './providers';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="flex h-full flex-col">
        <Providers>
          {/*<ViewTransition>*/}
            {children}
          {/*</ViewTransition>*/}
        </Providers>
      </body>
    </html>
  );
}
