/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces the current user belongs to */
        get: operations["WorkspaceController_listMine"];
        put?: never;
        /** Create a workspace owned by the current user */
        post: operations["WorkspaceController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a workspace and its members */
        get: operations["WorkspaceController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspace members */
        get: operations["WorkspaceController_listMembers"];
        put?: never;
        /** Add an existing user to the workspace */
        post: operations["WorkspaceController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a member's role */
        patch: operations["WorkspaceController_updateMemberRole"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from the workspace */
        delete: operations["WorkspaceController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave a workspace (owners must delete it instead) */
        delete: operations["WorkspaceController_leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/widget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get this workspace's widget configuration */
        get: operations["WidgetController_getOne"];
        put?: never;
        /** Create the support widget for this workspace */
        post: operations["WidgetController_create"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update this workspace's widget configuration */
        patch: operations["WidgetController_update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/widget/rotate-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the public widget key (invalidates the old embed script) */
        post: operations["WidgetController_rotateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/widget/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the public config for an embedded widget */
        get: operations["WidgetPublicController_getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/knowledge-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge base sources */
        get: operations["KnowledgeBaseController_list"];
        put?: never;
        /** Add a knowledge base source and queue it for indexing */
        post: operations["KnowledgeBaseController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/knowledge-sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a knowledge base source and its documents/chunks */
        delete: operations["KnowledgeBaseController_remove"];
        options?: never;
        head?: never;
        /** Update a knowledge base source */
        patch: operations["KnowledgeBaseController_update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/knowledge-sources/{sourceId}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-queue a source for indexing */
        post: operations["KnowledgeBaseController_reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/knowledge-sources/{sourceId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents indexed from a source */
        get: operations["KnowledgeBaseController_listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/escalation-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List escalation channels */
        get: operations["EscalationController_listChannels"];
        put?: never;
        /** Add an escalation channel */
        post: operations["EscalationController_createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/escalation-channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable/disable an escalation channel */
        patch: operations["EscalationController_updateChannel"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List escalations */
        get: operations["EscalationController_listEscalations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/escalations/{escalationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign or resolve an escalation */
        patch: operations["EscalationController_updateEscalation"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations for this workspace */
        get: operations["ConversationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a conversation */
        get: operations["ConversationController_listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/widget/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new widget conversation */
        post: operations["ConversationPublicController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/widget/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a visitor message and get the AI response */
        post: operations["ConversationPublicController_postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example test@gmail.com */
            email: string;
            /** @example password1 */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
        };
        LoginDto: {
            /** @example test@gmail.com */
            email: string;
            /** @example Password1 */
            password: string;
        };
        VerifyOtpDto: {
            /** @example test@gmail.com */
            email: string;
            otpCode: string;
        };
        ResendOtpDto: {
            /** @example test@gmail.com */
            email: string;
        };
        MeResponseDto: {
            id: string;
            email: string;
            firstName: Record<string, never> | null;
            lastName: Record<string, never> | null;
            confirmed: boolean;
            lastActiveWorkspaceId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateWorkspaceDto: {
            /** @example Acme Support */
            name: string;
        };
        WorkspaceMemberResponseDto: {
            id: string;
            workspaceId: string;
            userId: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "AGENT" | "VIEWER";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspaceWithMembersResponseDto: {
            id: string;
            name: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            members: components["schemas"]["WorkspaceMemberResponseDto"][];
        };
        PageMetaDto: {
            page: number;
            take: number;
            itemCount: number;
            pageCount: number;
        };
        PageDto: {
            data: unknown[][];
            meta: components["schemas"]["PageMetaDto"];
        };
        WorkspaceSummaryResponseDto: {
            id: string;
            name: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description The current user's role in the workspace
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "AGENT" | "VIEWER";
        };
        WorkspaceMemberUserResponseDto: {
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
        };
        WorkspaceMemberWithUserResponseDto: {
            id: string;
            workspaceId: string;
            userId: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "AGENT" | "VIEWER";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["WorkspaceMemberUserResponseDto"];
        };
        AddWorkspaceMemberDto: {
            /** @example teammate@example.com */
            email: string;
            /**
             * @example AGENT
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "AGENT" | "VIEWER";
        };
        UpdateWorkspaceMemberRoleDto: {
            /**
             * @example ADMIN
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "AGENT" | "VIEWER";
        };
        MessageResponse: {
            message: string;
        };
        WidgetResponseDto: {
            widgetKey: string;
            brandName: string;
            chatTitle: string;
            brandingSubtitle: string;
            welcomeMessage: string;
            handoffLabel: string;
            logoUrl: string | null;
            avatarUrl: string | null;
            primaryColor: string;
            secondaryColor: string;
            secondaryColorDark: string;
            /** @enum {string} */
            theme: "AUTO" | "LIGHT" | "DARK";
            /** @enum {string} */
            position: "BOTTOM_RIGHT" | "BOTTOM_LEFT";
            /** @enum {string} */
            launcherStyle: "CHAT_BUBBLE" | "BUTTON" | "TEXT_LINK";
            autoOpen: boolean;
            autoOpenDelaySeconds: number;
            showLauncherOnMobile: boolean;
            playSound: boolean;
            requirePreChatForm: boolean;
            identityVerification: boolean;
            requireCookieConsent: boolean;
            enableCaptcha: boolean;
            customCss: string | null;
            zIndex: number;
            hideBranding: boolean;
            language: string;
            id: string;
            workspaceId: string;
            isEnabled: boolean;
            allowedDomains: string[];
            /** @enum {string} */
            aiTone: "FRIENDLY" | "PROFESSIONAL" | "CASUAL" | "FORMAL";
            /** @enum {string} */
            fallbackAction: "SHOW_MESSAGE" | "ESCALATE_HUMAN" | "COLLECT_EMAIL" | "DO_NOTHING";
            customFallbackMessage: string | null;
            systemPrompt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateWidgetConfigDto: {
            /** @example Acme Support */
            brandName?: string;
            /** @example Acme Support */
            chatTitle?: string;
            /** @example We usually reply in a few minutes */
            brandingSubtitle?: string;
            /** @example Hi! How can we help you today? 😊 */
            welcomeMessage?: string;
            /** @example Talk to human */
            handoffLabel?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
            /** @example https://example.com/avatar.png */
            avatarUrl?: string;
            /** @example #7C5AED */
            primaryColor?: string;
            /** @example #EDEDED */
            secondaryColor?: string;
            /** @example #2D2D3F */
            secondaryColorDark?: string;
            /** @enum {string} */
            theme?: "AUTO" | "LIGHT" | "DARK";
            /** @enum {string} */
            position?: "BOTTOM_RIGHT" | "BOTTOM_LEFT";
            /** @enum {string} */
            launcherStyle?: "CHAT_BUBBLE" | "BUTTON" | "TEXT_LINK";
            autoOpen?: boolean;
            /** @enum {number} */
            autoOpenDelaySeconds?: 0 | 3 | 5 | 10 | 30;
            showLauncherOnMobile?: boolean;
            playSound?: boolean;
            requirePreChatForm?: boolean;
            /**
             * @example [
             *       "example.com"
             *     ]
             */
            allowedDomains?: string[];
            identityVerification?: boolean;
            requireCookieConsent?: boolean;
            enableCaptcha?: boolean;
            customCss?: string;
            zIndex?: number;
            hideBranding?: boolean;
            /** @enum {string} */
            aiTone?: "FRIENDLY" | "PROFESSIONAL" | "CASUAL" | "FORMAL";
            /** @example en */
            language?: string;
            /** @enum {string} */
            fallbackAction?: "SHOW_MESSAGE" | "ESCALATE_HUMAN" | "COLLECT_EMAIL" | "DO_NOTHING";
            /** @example Sorry, I couldn't find an answer to your question. */
            customFallbackMessage?: string;
            /** @description Persona/system prompt steering the AI assistant */
            systemPrompt?: string;
        };
        WidgetPublicConfigResponseDto: {
            widgetKey: string;
            brandName: string;
            chatTitle: string;
            brandingSubtitle: string;
            welcomeMessage: string;
            handoffLabel: string;
            logoUrl: string | null;
            avatarUrl: string | null;
            primaryColor: string;
            secondaryColor: string;
            secondaryColorDark: string;
            /** @enum {string} */
            theme: "AUTO" | "LIGHT" | "DARK";
            /** @enum {string} */
            position: "BOTTOM_RIGHT" | "BOTTOM_LEFT";
            /** @enum {string} */
            launcherStyle: "CHAT_BUBBLE" | "BUTTON" | "TEXT_LINK";
            autoOpen: boolean;
            autoOpenDelaySeconds: number;
            showLauncherOnMobile: boolean;
            playSound: boolean;
            requirePreChatForm: boolean;
            identityVerification: boolean;
            requireCookieConsent: boolean;
            enableCaptcha: boolean;
            customCss: string | null;
            zIndex: number;
            hideBranding: boolean;
            language: string;
        };
        FaqItemDto: {
            /** @example What is your refund policy? */
            question: string;
            /** @example We offer full refunds within 30 days of purchase. */
            answer: string;
        };
        CreateKnowledgeSourceDto: {
            /**
             * @example MANUAL
             * @enum {string}
             */
            type: "WEBSITE" | "FILE" | "FAQ" | "MANUAL";
            /** @example Refund Policy */
            name: string;
            /** @description Required for WEBSITE sources */
            url?: string;
            /** @description Required for MANUAL sources */
            content?: string;
            /** @description Required for FAQ sources */
            items?: components["schemas"]["FaqItemDto"][];
        };
        KnowledgeSourceResponseDto: {
            id: string;
            workspaceId: string;
            /** @enum {string} */
            type: "WEBSITE" | "FILE" | "FAQ" | "MANUAL";
            name: string;
            url: string | null;
            /** @enum {string} */
            status: "PENDING" | "INDEXING" | "ACTIVE" | "INACTIVE" | "ERROR";
            error: string | null;
            /** @description Content for MANUAL sources */
            content: string | null;
            /** @description Q&A pairs for FAQ sources */
            items: components["schemas"]["FaqItemDto"][] | null;
            documentsCount: number;
            chunksCount: number;
            /** Format: date-time */
            lastIndexedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        KnowledgeSourceListMetaDto: {
            page: number;
            take: number;
            itemCount: number;
            pageCount: number;
            /** @description Total documents across all sources in the workspace */
            documentsCount: number;
            /** @description Total chunks across all sources in the workspace */
            chunksCount: number;
        };
        KnowledgeSourceListResponseDto: {
            data: components["schemas"]["KnowledgeSourceResponseDto"][];
            meta: components["schemas"]["KnowledgeSourceListMetaDto"];
        };
        UpdateKnowledgeSourceDto: {
            /** @example Refund Policy */
            name?: string;
            /** @description Only applies to WEBSITE sources */
            url?: string;
            /** @description Only applies to MANUAL sources */
            content?: string;
            /** @description Only applies to FAQ sources */
            items?: components["schemas"]["FaqItemDto"][];
        };
        KnowledgeDocumentResponseDto: {
            id: string;
            sourceId: string;
            title: string;
            sourceUri: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateEscalationChannelDto: {
            /**
             * @example WEBHOOK
             * @enum {string}
             */
            destination: "TELEGRAM" | "EMAIL" | "WEBHOOK" | "EXTERNAL_CHAT";
            /** @description Required for WEBHOOK channels */
            url?: string;
            /** @description Required for EMAIL channels */
            email?: string;
            /** @description Required for TELEGRAM channels */
            chatId?: string;
        };
        EscalationChannelResponseDto: {
            id: string;
            workspaceId: string;
            /** @enum {string} */
            destination: "TELEGRAM" | "EMAIL" | "WEBHOOK" | "EXTERNAL_CHAT";
            isEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateEscalationChannelDto: {
            isEnabled?: boolean;
        };
        EscalationResponseDto: {
            id: string;
            conversationId: string;
            workspaceId: string;
            /** @enum {string} */
            status: "WAITING_HUMAN" | "IN_PROGRESS" | "RESOLVED";
            /** @enum {string} */
            reason: "LOW_CONFIDENCE" | "USER_REQUEST" | "FALLBACK_RULE";
            channelId: string | null;
            assignedToUserId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateEscalationDto: {
            /** @enum {string} */
            status?: "WAITING_HUMAN" | "IN_PROGRESS" | "RESOLVED";
            /** @description User id of the agent handling this escalation */
            assignedToUserId?: string;
        };
        ConversationResponseDto: {
            id: string;
            widgetId: string;
            visitorId: string;
            /** @enum {string} */
            status: "OPEN" | "ESCALATED" | "RESOLVED" | "CLOSED";
            aiSummary: string | null;
            /** Format: date-time */
            lastMessageAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationMessageResponseDto: {
            id: string;
            /** @enum {string} */
            role: "VISITOR" | "ASSISTANT" | "HUMAN_AGENT" | "SYSTEM";
            content: string;
            confidence: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        VisitorPayloadDto: {
            /** @description Stable visitor id from the host site (e.g. logged-in user id) */
            externalId?: string;
            email?: string;
            name?: string;
        };
        CreateConversationDto: {
            /** @example pub_... */
            widgetKey: string;
            visitor?: components["schemas"]["VisitorPayloadDto"];
        };
        CreateConversationResponseDto: {
            conversationId: string;
            visitorId: string;
        };
        CreateMessageDto: {
            /** @example pub_... */
            widgetKey: string;
            /** @example How do I reset my password? */
            content: string;
        };
        MessageItemDto: {
            id: string;
            /** @enum {string} */
            role: "VISITOR" | "ASSISTANT" | "HUMAN_AGENT" | "SYSTEM";
            content: string;
        };
        CreateMessageResponseDto: {
            userMessage: components["schemas"]["MessageItemDto"];
            assistantMessage: components["schemas"]["MessageItemDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    WorkspaceController_listMine: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["WorkspaceSummaryResponseDto"][];
                    };
                };
            };
        };
    };
    WorkspaceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceWithMembersResponseDto"];
                };
            };
            /** @description Maximum number of owned workspaces reached */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceWithMembersResponseDto"];
                };
            };
            /** @description You do not have access to this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceController_listMembers: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["WorkspaceMemberWithUserResponseDto"][];
                    };
                };
            };
            /** @description You do not have access to this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkspaceMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberResponseDto"];
                };
            };
            /** @description Cannot assign the owner role, or user is already a member */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceMemberRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberResponseDto"];
                };
            };
            /** @description Cannot assign the owner role */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requires at least the ADMIN workspace role, or target member is the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workspace member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role, or target member is the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workspace member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description You do not have access to this workspace, or you are the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Membership not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WidgetController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetResponseDto"];
                };
            };
            /** @description You do not have access to this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Widget not found for this workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WidgetController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetResponseDto"];
                };
            };
            /** @description This workspace already has a widget */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WidgetController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWidgetConfigDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Widget not found for this workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WidgetController_rotateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Widget not found for this workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WidgetPublicController_getConfig: {
        parameters: {
            query: {
                widgetKey: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetPublicConfigResponseDto"];
                };
            };
            /** @description Origin not allowed for this widget */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Widget not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_list: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSourceListResponseDto"];
                };
            };
        };
    };
    KnowledgeBaseController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeSourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSourceResponseDto"];
                };
            };
            /** @description Invalid or unsupported source payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSourceResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Knowledge source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKnowledgeSourceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSourceResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Knowledge source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_reindex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSourceResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Knowledge source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_listDocuments: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["KnowledgeDocumentResponseDto"][];
                    };
                };
            };
            /** @description Knowledge source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_listChannels: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["EscalationChannelResponseDto"][];
                    };
                };
            };
        };
    };
    EscalationController_createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEscalationChannelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationChannelResponseDto"];
                };
            };
            /** @description Requires at least the ADMIN workspace role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                channelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEscalationChannelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationChannelResponseDto"];
                };
            };
            /** @description Escalation channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_listEscalations: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["EscalationResponseDto"][];
                    };
                };
            };
        };
    };
    EscalationController_updateEscalation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                escalationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEscalationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationResponseDto"];
                };
            };
            /** @description Escalation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationController_list: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["ConversationResponseDto"][];
                    };
                };
            };
            /** @description You do not have access to this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationController_listMessages: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                /** @description Field to sort by */
                orderBy?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path: {
                workspaceId: string;
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["ConversationMessageResponseDto"][];
                    };
                };
            };
            /** @description You do not have access to this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationPublicController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateConversationResponseDto"];
                };
            };
            /** @description Origin not allowed for this widget */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Widget not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConversationPublicController_postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMessageResponseDto"];
                };
            };
            /** @description Origin not allowed for this widget */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Widget or conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many messages, please slow down */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
